[project]
name = "full-esp32-pio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "netifaces>=0.11.0",
    "zeroconf>=0.148.0",
]
