#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := hello-world

IDF_PATH := /home/mgr/Programs/esp-idf

include $(IDF_PATH)/make/project.mk

